name: Analog Publish GitHub Pages
description: Build a static AnalogJS site and deploy it on GitHub Pages
author: Danny Koppenhagen <mail@k9n.dev>
branding:
  icon: heart
  color: green
inputs:
  package-manager:
    description: The package manager to be used (npm, yarn, pnpm)
    required: false
    default: npm
  access-token:
    description: A personal access token needed to push your site after it has been built.
    required: true
  install-args:
    description: Additional arguments that get passed to `npm ci` (e. g. `--legacy-peer-deps`).
    required: false
    default: ""
  build-args:
    description: Additional arguments that get passed to `npm run build`.
    required: false
    default: ""
  deploy-dir:
    description: The path to the directory to deploy
    required: false
    default: dist/analog/public
  deploy-branch:
    description: The branch where the static site should be deployed
    required: false
    default: gh-pages
  dry-run:
    description: Don't actually deploy
    required: false
    default: "false"
runs:
  using: node20
  main: dist/index.js
