name: 'Analog Publish Github Pages'
description: 'Build a static Analog.js site and deploy it on Github Pages'
author: 'Danny Koppenhagen <mail@k9n.dev>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'green'

# Define your inputs here.
inputs:
  package-manager:
    description: "The package manager to be used (npm, yarn, pnpm)"
    required: false
    default: "npm"
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: true
  install-args:
    description: "Additional arguments that get passed to `npm ci` (e. g. `--legacy-peer-deps`)."
    required: false
    default: ""
  build-args:
    description: "Additional arguments that get passed to `npm run build`."
    required: false
    default: ""
  deploy-dir:
    description: "The path to the directory to deploy"
    required: false
    default: "dist/analog/public"
  deploy-args:
    description: "Additional arguments that get passed to `npx angular-cli-ghpages`."
    required: false
    default: "--no-silent"

runs:
  using: node20
  main: dist/index.js
